apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName.backend }}-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName.backend }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName.backend }}
    spec:
      containers:
        - name: {{ .Values.appName.backend }}
          image: ghislaingenay/{{ .Values.containers.backend.image }}
          env:
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: ACCESS_TOKEN
                  name: mk-secret
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName.backend }}-svc
spec:
  selector:
    app: {{ .Values.appName.backend }}
  ports:
    - name: {{ .Values.appName.backend }}
      protocol: TCP
      port: 3000
      targetPort: 3000
