apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.hostSecret }}-tls"
  annotations:
    meta.helm.sh/release-name: "mk-release"
    meta.helm.sh/release-namespace: "default"
spec:
  secretName: "{{ .Values.hostSecret }}"
  issuerRef:
    name: "{{ .Values.issuer.key }}"
    kind: ClusterIssuer
  commonName: "{{ .Values.baseDomain }}"
  dnsNames:
    - "{{ .Values.baseDomain }}"
    - "{{ .Values.baseWwwDomain }}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.hostApiSecret }}-tls"
  annotations:
    meta.helm.sh/release-name: "mk-release"
    meta.helm.sh/release-namespace: "default"
spec:
  secretName: "{{ .Values.hostApiSecret }}"
  issuerRef:
    name: "{{ .Values.issuer.key }}"
    kind: ClusterIssuer
  commonName: "{{ .Values.baseApiDomain }}"
  dnsNames:
    - "{{ .Values.baseApiDomain }}"
