apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName.client }}-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName.client }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Values.appName.client }}
    spec:
      containers:
        - name: {{ .Values.appName.client }}
          image: ghislaingenay/{{ .Values.containers.client.image }}
          ports:
            - containerPort: 3000
          env:
            - name: VITE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: VITE_ACCESS_TOKEN
                  name: mk-secret
            - name: VITE_BACK_END
              valueFrom:
                secretKeyRef:
                  key: VITE_BACK_END
                  name: mk-secret
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName.client }}-svc
spec:
  selector:
    app: {{ .Values.appName.client }}
  ports:
    - name: {{ .Values.appName.client }}
      protocol: TCP
      port: 3000
      targetPort: 3000
