apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: {{ .Values.issuer.key }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  #ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.baseDomain }}
        - {{ .Values.baseWwwDomain }}
      secretName: {{ .Values.hostSecret }}
  rules:
    - host: {{ .Values.baseDomain }}
      http:
        paths:
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.appName.backend }}-svc
                port:
                  number: 8000
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.appName.client }}-svc
                port:
                  number: 3000
    - host: {{ .Values.baseWwwDomain }}
      http:
        paths:
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.appName.backend }}-svc
                port:
                  number: 8000
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.appName.client }}-svc
                port:
                  number: 3000
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: acme-challenge-ingress
#   namespace: default
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/acme-challenge: "true"
# spec:
#   rules:
#     - host: mk.staging.redicoding.com
#       http:
#         paths:
#           - path: /.well-known/acme-challenge/*
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: cert-manager
#                 port:
#                   number: 8089