apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{ .Values.issuer.key }}"
spec:
  acme:
    email: "{{ .Values.issuer.email }}"
    server: "{{ .Values.issuer.server }}"
    privateKeySecretRef:
      name: "{{ .Values.issuer.key }}"
    solvers:
      - http01:
          ingress:
            class: nginx
